variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
#  - sonarqube

build:
  stage: build
  tags:
    - shared
  script:
    - cd CopacoProject
    - ./gradlew clean
    - ./gradlew assemble

test:
  stage: test
  tags:
    - shared
  script:
    - cd CopacoProject
    - ./gradlew test

#sonarqube:
#  stage: sonarqube
#  tags:
#    - shared
#  variables:
#    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
#    GIT_DEPTH: "0"
#  cache:
#    key: "${CI_JOB_NAME}"
#    paths:
#      - .sonar/cache
#  script:
#    -  cd CopacoProject
#    - ./gradlew clean test jacocoTestReport
#    - ./gradlew sonar "-Dsonar.host.url=http://localhost:9000" "-Dsonar.token=sqp_5daf6275312c253fa0b42828a8223404380d2a1e" "-Dsonar.qualitygate.wait=true"
#  allow_failure: false