variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube

build:
  stage: build
  tags:
    - copaco_runner
  script:
    - cd CopacoProject
    - chmod +x ./gradlew
    - ./gradlew clean
    - ./gradlew assemble

test:
  stage: test
  tags:
    - copaco_runner
  script:
    - cd CopacoProject
    - chmod +x ./gradlew
    - ./gradlew test

sonarqube:
  stage: sonarqube
  tags:
    - copaco_runner
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    -  cd CopacoProject
    - ./gradlew clean test jacocoTestReport
    - ./gradlew sonar "-Dsonar.host.url=http://localhost:9000" "-Dsonar.token=sqp_5daf6275312c253fa0b42828a8223404380d2a1e" "-Dsonar.qualitygate.wait=true"
  allow_failure: false