variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
#  - build
#  - test
  - sonarqube

#build:
#  stage: build
#  tags:
#    - shared
#  script:
#    - cd CopacoProject
#    - ./gradlew clean
#    - ./gradlew assemble

#test:
#  stage: test
#  tags:
#    - shared
#  script:
#    - cd CopacoProject
#    - ./gradlew test


sonarqube:
  stage: sonarqube
  tags:
    - shared
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    -  cd CopacoProject
    - ./gradlew clean test jacocoTestReport
    - ./gradlew sonar "-Dsonar.host.url=http://localhost:9000" "-Dsonar.token=sqp_acf29ea2b2067e85eea187d18c881fc001652408" "-Dsonar.qualitygate.wait=true"
  allow_failure: false